version: "3.7"
services:
    node:
        build: .
        image: node:latest
        volumes:
            - .:/usr/app/
        working_dir: /usr/app/
        ports: 
            - "5000:5000"
        command: npm run dev
        env_file: 
            - .env